apiVersion: v1
kind: Service
metadata:
  name: srv-<%=name%>
  namespace: <%=ocNamespaceQA%>
  labels:
    app: <%=name%>
    version: <%=version%>
    environment: <%=ocNamespaceQA%>
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 80
    nodePort: 30009
    protocol: TCP
    targetPort: port-<%=name %>
  selector:
    app: <%=name%>
    version: <%=version%>
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

