apiVersion: v1
kind: Service
metadata:
  name: srv-<%=name%>
  namespace: <%=ocNamespacePRD%>
  labels:
    app: <%=name%>
    version: <%=version%>
    environment: <%=ocNamespacePRD%>
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 80
    nodePort: 31008
    protocol: TCP
    targetPort: port-<%=name%>
  selector:
    app: <%=name%>
    version: <%=version%>
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
